"""Deterministic Markdown renderer for HowlRelay artifacts."""

from howlrelay.model import HandoffEnvelope, WorkState


def render_handoff(envelope: HandoffEnvelope) -> str:
    """Render a comprehensive, grounded asynchronous handoff document."""
    ws = envelope.work_state
    lines = []

    lines.append(f"# Asynchronous Handoff: {ws.repo_name}")
    lines.append(f"*Generated by HowlRelay v{envelope.generator_version} at {ws.gathered_at}*")
    lines.append("")

    # Objective & State
    lines.append("## Objective")
    lines.append(ws.work_item.objective)
    lines.append("")

    lines.append("## Current State")
    lines.append(f"- **Status:** `{ws.status.value.upper()}`")
    lines.append(f"- **Confidence:** `{ws.confidence.value.upper()}`")
    lines.append(f"- **Repository Root:** `{ws.repo_root}`")
    lines.append("")

    # Meeting Recommendation
    lines.append("## Synchronous Meeting Recommendation")
    lines.append(f"- **Recommendation:** `{ws.meeting.recommendation.value}`")
    lines.append(f"- **Reasoning:** {ws.meeting.reason}")
    if ws.meeting.triggers:
        lines.append(f"- **Triggers:** {', '.join(ws.meeting.triggers)}")
    lines.append("")

    # Completed & Incomplete Work
    lines.append("## What Is Complete")
    if ws.completed:
        for item in ws.completed:
            lines.append(f"- [x] {item}")
    else:
        lines.append("- None explicitly recorded.")
    lines.append("")

    lines.append("## What Remains Incomplete / Active")
    if ws.active_work:
        for item in ws.active_work:
            lines.append(f"- [ ] {item}")
    else:
        lines.append("- No active items explicitly tracked.")
    lines.append("")

    # Blockers & Risks
    lines.append("## Blockers")
    if ws.blockers:
        for b in ws.blockers:
            lines.append(f"- **[{b.severity.upper()}]** {b.description} *(Reason: {b.reason})*")
    else:
        lines.append("- None detected.")
    lines.append("")

    lines.append("## Decisions Made")
    if ws.decisions:
        for d in ws.decisions:
            status_tag = f"[{d.status}]" if d.status else "[DECIDED]"
            lines.append(f"- **{status_tag}** {d.decision}")
            lines.append(f"  - *Rationale:* {d.rationale}")
            if d.evidence_refs:
                lines.append(f"  - *Evidence:* {', '.join(d.evidence_refs)}")
    else:
        lines.append("- No explicit decisions recorded in DECISIONS.md.")
    lines.append("")

    # Files / Components Involved
    lines.append("## Files & Components Involved")
    if envelope.files_involved:
        for f in sorted(envelope.files_involved):
            lines.append(f"- `{f}`")
    else:
        lines.append("- Working tree clean; no uncommitted files.")
    lines.append("")

    # Verification & Tests
    lines.append("## Test & Verification Status")
    lines.append(f"- **Status:** `{envelope.test_status}`")
    if envelope.known_failures:
        lines.append("- **Known Failures:**")
        for kf in envelope.known_failures:
            lines.append(f"  - {kf}")
    if envelope.tests_run:
        lines.append("- **Verification Runs:**")
        for tr in envelope.tests_run:
            summary = tr.get('summary', 'n/a')
            exit_code = tr.get('exit_code')
            lines.append(f"  - Summary: {summary} (Exit code: {exit_code})")
    lines.append("")

    # Next Recommended Actions
    lines.append("## Next Recommended Actions")
    if ws.next_actions:
        for na in ws.next_actions:
            owner_str = f" (Owner: {na.owner})" if na.owner else ""
            lines.append(f"- **[{na.priority.upper()}]** {na.action}{owner_str}")
    else:
        lines.append("- None explicitly specified.")
    lines.append("")

    # Starting Commands
    lines.append("## Exact Starting Commands")
    if envelope.exact_starting_commands:
        lines.append("```bash")
        for cmd in envelope.exact_starting_commands:
            lines.append(cmd)
        lines.append("```")
    else:
        lines.append("```bash")
        lines.append(f"cd {ws.repo_root}")
        lines.append("git status")
        lines.append("```")
    lines.append("")

    # Continuation Instructions
    if envelope.continuation_instructions:
        lines.append("## Continuation Context & Instructions")
        for ci in envelope.continuation_instructions:
            lines.append(f"- {ci}")
        lines.append("")

    # Epistemic Partitioning: Observed Facts vs Inferred State vs Missing Information
    lines.append("## Epistemic Provenance")
    lines.append("### Observed Facts")
    for fact in envelope.observed_facts[:10]:
        lines.append(f"- {fact}")
    if len(envelope.observed_facts) > 10:
        lines.append(f"- *(and {len(envelope.observed_facts) - 10} more observed facts)*")
    lines.append("")

    lines.append("### Inferred State")
    for inf in envelope.inferred_state:
        lines.append(f"- {inf}")
    lines.append("")

    lines.append("### Missing Information (Unknowns)")
    if ws.missing_information:
        for miss in ws.missing_information:
            lines.append(f"- {miss}")
    else:
        lines.append("- No critical information gaps identified.")
    lines.append("")

    return "\n".join(lines)


def render_status(ws: WorkState) -> str:
    """Render a concise workstream status report."""
    lines = []
    lines.append(f"# Status: {ws.repo_name}")
    lines.append(f"**Objective:** {ws.work_item.objective}")
    lines.append(
        f"**Status:** `{ws.status.value.upper()}` | "
        f"**Confidence:** `{ws.confidence.value.upper()}`"
    )
    lines.append("")

    lines.append("### Synchronous Alignment")
    lines.append(f"- **Meeting Recommendation:** `{ws.meeting.recommendation.value}`")
    lines.append(f"- **Reason:** {ws.meeting.reason}")
    lines.append("")

    lines.append("### Completed Work")
    if ws.completed:
        for item in ws.completed:
            lines.append(f"- [x] {item}")
    else:
        lines.append("- None explicitly recorded.")
    lines.append("")

    lines.append("### Active Work")
    if ws.active_work:
        for item in ws.active_work:
            lines.append(f"- [ ] {item}")
    else:
        lines.append("- No active items tracked.")
    lines.append("")

    lines.append("### Blockers & Dependencies")
    if ws.blockers:
        for b in ws.blockers:
            lines.append(f"- **[BLOCKER - {b.severity.upper()}]** {b.description}")
    elif ws.dependencies:
        for d in ws.dependencies:
            lines.append(f"- [DEP] {d.item} (Owner: {d.owner}) - {d.status}")
    else:
        lines.append("- None active.")
    lines.append("")

    lines.append("### Next Actions")
    if ws.next_actions:
        for na in ws.next_actions:
            lines.append(f"- {na.action}")
    else:
        lines.append("- None recorded.")
    lines.append("")

    if ws.missing_information:
        lines.append("### Known Gaps / Unknowns")
        for m in ws.missing_information:
            lines.append(f"- {m}")
        lines.append("")

    return "\n".join(lines)


def render_brief(ws: WorkState) -> str:
    """Render an anti-activity-theater team brief for broader stakeholders."""
    lines = []
    lines.append(f"# Team Brief: {ws.repo_name}")
    lines.append(f"*As of {ws.gathered_at}*")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append(f"- **Objective:** {ws.work_item.objective}")
    lines.append(f"- **Health:** `{ws.status.value.upper()}` ({ws.confidence.value.upper()} conf)")
    lines.append(
        f"- **Meeting Required?** `{ws.meeting.recommendation.value}` — "
        f"{ws.meeting.reason}"
    )
    lines.append("")

    lines.append("## Meaningful Progress")
    if ws.completed:
        for item in ws.completed[-5:]:  # Recent 5 items to avoid activity theater
            lines.append(f"- {item}")
    else:
        lines.append("- Initializing milestone work.")
    lines.append("")

    lines.append("## Key Decisions")
    if ws.decisions:
        for d in ws.decisions[-3:]:
            lines.append(f"- **{d.decision}**: {d.rationale}")
    else:
        lines.append("- None recorded.")
    lines.append("")

    lines.append("## Blockers & Risk Changes")
    if ws.blockers:
        for b in ws.blockers:
            lines.append(f"- **Blocker:** {b.description}")
    if ws.risks:
        for r in ws.risks:
            lines.append(f"- **Risk [{r.level.upper()}]:** {r.description}")
    if not ws.blockers and not ws.risks:
        lines.append("- No critical blockers or unmitigated risks.")
    lines.append("")

    lines.append("## Requests for Action / Human Decisions Needed")
    unresolved = [d for d in ws.decisions if d.status.upper() in ("UNRESOLVED", "PROPOSED")]
    if unresolved:
        for u in unresolved:
            lines.append(f"- **Decision Needed:** {u.decision} ({u.rationale})")
    elif ws.next_actions:
        for na in ws.next_actions[:3]:
            lines.append(f"- Next: {na.action}")
    else:
        lines.append("- None at this time.")
    lines.append("")

    return "\n".join(lines)
